name: Deno

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest # runs a test on Ubuntu, Windows and macOS

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        run: |
